import { ListOfUtilities } from '@/components/ListOfUtilities'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function LayoutListUtilitiesPage ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <section className='flex justify-center items-center w-full'>
      <div className='flex justify-center max-w-7xl w-full px-10 md:grid md:grid-cols-[220px_1fr] md:gap-6 lg:grid-cols-[240px_1fr] lg:gap-10'>
        <ListOfUtilities />
        {children}
      </div>
    </section>
  )
}
